"""Transcribe the "More reactions…" catalogue from web/text/src/emoji.rs into win/src/FamilyConnect.Core/Text/EmojiCatalog.cs.

The catalogue is the apps' (ios Models/EmojiCatalog.swift, byte-identical to Android's EmojiCatalog.kt), and the web
crate transcribed it by script too. This does the same for Windows, writing each emoji as its SCALARS — so an invisible
U+FE0F cannot be lost in an editor — and the chat oracle's `emoji_catalog` section holds the result to Rust byte for byte.

    python3 win/tools/emoji/transcribe.py <repo>
"""
import pathlib
import re
import sys


def main() -> int:
    repo = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else ".")
    source = (repo / "web/text/src/emoji.rs").read_text(encoding="utf-8")
    block = source[source.index("pub static EMOJI_CATALOG"):]
    block = block[:block.index("\n];")]
    categories = re.findall(r'name:\s*"([^"]+)",\s*emoji:\s*&\[(.*?)\],', block, re.S)
    lines = [
        "// GENERATED by win/tools/emoji/transcribe.py from web/text/src/emoji.rs — do not edit by hand.",
        "namespace FamilyConnect.Core;",
        "",
        "/// <summary>One section of the \"More reactions…\" picker: its canonical name, which is also the key its header is said by, and its emoji in order.</summary>",
        "public sealed record EmojiCategory(string Name, IReadOnlyList<string> Emoji);",
        "",
        "/// <summary>",
        "/// The full picker behind \"More reactions…\": the apps' eight sections, transcribed as scalars from the web client's",
        "/// copy (<c>fc_text::emoji::EMOJI_CATALOG</c>) and held to it by the chat oracle.",
        "/// </summary>",
        "public static class EmojiCatalog",
        "{",
        "    private static string E(params int[] scalars) => string.Concat(scalars.Select(char.ConvertFromUtf32));",
        "",
        "    public static IReadOnlyList<EmojiCategory> Categories { get; } =",
        "    [",
    ]
    total = 0
    for name, body in categories:
        emoji = re.findall(r'"((?:[^"\\]|\\.)*)"', body)
        total += len(emoji)
        lines.append(f'        new("{name}",')
        lines.append("        [")
        row = []
        for item in emoji:
            if "\\" in item:
                raise SystemExit(f"an escape in the catalogue is not expected: {item!r}")
            scalars = ", ".join(f"0x{ord(c):X}" for c in item)
            row.append(f"E({scalars})")
            if len(row) == 6:
                lines.append("            " + ", ".join(row) + ",")
                row = []
        if row:
            lines.append("            " + ", ".join(row) + ",")
        lines.append("        ]),")
    lines.append("    ];")
    lines.append("}")
    target = repo / "win/src/FamilyConnect.Core/Text/EmojiCatalog.cs"
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{len(categories)} sections, {total} emoji -> {target}")
    return 0 if len(categories) == 8 else 1


if __name__ == "__main__":
    sys.exit(main())
