//! GENERATED — do not edit. `server/i18n/generate.py` writes it from the apps'
//! `Localizable.xcstrings` and `server/i18n/push.json` (docs/protocol.md, "The words
//! of a push"). A key is the ENGLISH sentence, which is also what a device with no
//! language, or one this table does not know, is sent.

/// (key, language, words), sorted by key and then language, so a lookup is a binary search.
pub(crate) static TABLE: &[(&str, &str, &str)] = &[
    ("%@ asked to join", "de", "%@ möchte beitreten"),
    ("%@ asked to join", "es", "%@ pidió unirse"),
    (
        "%@ asked to join",
        "fr",
        "%@ demande à rejoindre la famille",
    ),
    ("%@ asked to join", "ja", "%@が参加をリクエストしました"),
    ("%@ asked to join", "ru", "%@ просит вступить в семью"),
    ("%@ asked to join", "sr", "%@ тражи да се придружи"),
    ("%@ asked to join", "sr-Latn", "%@ traži da se pridruži"),
    ("%@ asked to join", "zh-Hans", "%@ 请求加入"),
    ("%@ — %@ mentioned you", "de", "%@ — %@ hat dich erwähnt"),
    ("%@ — %@ mentioned you", "es", "%@ — %@ te mencionó"),
    ("%@ — %@ mentioned you", "fr", "%@ — %@ vous a mentionné"),
    (
        "%@ — %@ mentioned you",
        "ja",
        "%@ — %@があなたをメンションしました",
    ),
    ("%@ — %@ mentioned you", "ru", "%@ — %@ упоминает тебя"),
    ("%@ — %@ mentioned you", "sr", "%@ — %@ те је поменуо/ла"),
    (
        "%@ — %@ mentioned you",
        "sr-Latn",
        "%@ — %@ te je pomenuo/la",
    ),
    ("%@ — %@ mentioned you", "zh-Hans", "%@ — %@ 提到了你"),
    ("%lld Audio", "de", "%lld Audios"),
    ("%lld Audio", "es", "%lld audios"),
    ("%lld Audio", "fr", "%lld audios"),
    ("%lld Audio", "ja", "音声%lld件"),
    ("%lld Audio", "ru", "%lld аудио"),
    ("%lld Audio", "sr", "аудио записа: %lld"),
    ("%lld Audio", "sr-Latn", "audio zapisa: %lld"),
    ("%lld Audio", "zh-Hans", "%lld段音频"),
    ("%lld Files", "de", "%lld Dateien"),
    ("%lld Files", "es", "%lld archivos"),
    ("%lld Files", "fr", "%lld fichiers"),
    ("%lld Files", "ja", "ファイル%lld件"),
    ("%lld Files", "ru", "Файлов: %lld"),
    ("%lld Files", "sr", "датотека: %lld"),
    ("%lld Files", "sr-Latn", "datoteka: %lld"),
    ("%lld Files", "zh-Hans", "%lld个文件"),
    ("%lld Photos", "de", "%lld Fotos"),
    ("%lld Photos", "es", "%lld fotos"),
    ("%lld Photos", "fr", "%lld photos"),
    ("%lld Photos", "ja", "写真%lld枚"),
    ("%lld Photos", "ru", "%lld фото"),
    ("%lld Photos", "sr", "фотографија: %lld"),
    ("%lld Photos", "sr-Latn", "fotografija: %lld"),
    ("%lld Photos", "zh-Hans", "%lld张照片"),
    ("%lld Videos", "de", "%lld Videos"),
    ("%lld Videos", "es", "%lld vídeos"),
    ("%lld Videos", "fr", "%lld vidéos"),
    ("%lld Videos", "ja", "動画%lld本"),
    ("%lld Videos", "ru", "%lld видео"),
    ("%lld Videos", "sr", "видео снимака: %lld"),
    ("%lld Videos", "sr-Latn", "video snimaka: %lld"),
    ("%lld Videos", "zh-Hans", "%lld个视频"),
    ("%lld attachments", "de", "%lld Anhänge"),
    ("%lld attachments", "es", "%lld adjuntos"),
    ("%lld attachments", "fr", "%lld pièces jointes"),
    ("%lld attachments", "ja", "添付ファイル%lld件"),
    ("%lld attachments", "ru", "Вложений: %lld"),
    ("%lld attachments", "sr", "прилога: %lld"),
    ("%lld attachments", "sr-Latn", "priloga: %lld"),
    ("%lld attachments", "zh-Hans", "%lld个附件"),
    ("Audio", "de", "Audio"),
    ("Audio", "es", "Audio"),
    ("Audio", "fr", "Audio"),
    ("Audio", "ja", "オーディオ"),
    ("Audio", "ru", "Аудио"),
    ("Audio", "sr", "Аудио"),
    ("Audio", "sr-Latn", "Audio"),
    ("Audio", "zh-Hans", "音频"),
    ("File", "de", "Datei"),
    ("File", "es", "Archivo"),
    ("File", "fr", "Fichier"),
    ("File", "ja", "ファイル"),
    ("File", "ru", "Файл"),
    ("File", "sr", "Датотека"),
    ("File", "sr-Latn", "Datoteka"),
    ("File", "zh-Hans", "文件"),
    ("Location", "de", "Standort"),
    ("Location", "es", "Ubicación"),
    ("Location", "fr", "Position"),
    ("Location", "ja", "位置情報"),
    ("Location", "ru", "Местоположение"),
    ("Location", "sr", "Локација"),
    ("Location", "sr-Latn", "Lokacija"),
    ("Location", "zh-Hans", "位置"),
    ("New message", "de", "Neue Nachricht"),
    ("New message", "es", "Mensaje nuevo"),
    ("New message", "fr", "Nouveau message"),
    ("New message", "ja", "新着メッセージ"),
    ("New message", "ru", "Новое сообщение"),
    ("New message", "sr", "Нова порука"),
    ("New message", "sr-Latn", "Nova poruka"),
    ("New message", "zh-Hans", "新消息"),
    ("New note", "de", "Neue Notiz"),
    ("New note", "es", "Nueva nota"),
    ("New note", "fr", "Nouvelle note"),
    ("New note", "ja", "新しいメモ"),
    ("New note", "ru", "Новая заметка"),
    ("New note", "sr", "Нова белешка"),
    ("New note", "sr-Latn", "Nova beleška"),
    ("New note", "zh-Hans", "新便签"),
    ("New report", "de", "Neue Meldung"),
    ("New report", "es", "Nueva denuncia"),
    ("New report", "fr", "Nouveau signalement"),
    ("New report", "ja", "新しい報告"),
    ("New report", "ru", "Новая жалоба"),
    ("New report", "sr", "Нова пријава"),
    ("New report", "sr-Latn", "Nova prijava"),
    ("New report", "zh-Hans", "新举报"),
    ("Photo", "de", "Foto"),
    ("Photo", "es", "Foto"),
    ("Photo", "fr", "Photo"),
    ("Photo", "ja", "写真"),
    ("Photo", "ru", "Фото"),
    ("Photo", "sr", "Фотографија"),
    ("Photo", "sr-Latn", "Fotografija"),
    ("Photo", "zh-Hans", "照片"),
    ("Sticker", "de", "Sticker"),
    ("Sticker", "es", "Sticker"),
    ("Sticker", "fr", "Sticker"),
    ("Sticker", "ja", "スタンプ"),
    ("Sticker", "ru", "Стикер"),
    ("Sticker", "sr", "Стикер"),
    ("Sticker", "sr-Latn", "Stiker"),
    ("Sticker", "zh-Hans", "贴纸"),
    ("Video", "de", "Video"),
    ("Video", "es", "Vídeo"),
    ("Video", "fr", "Vidéo"),
    ("Video", "ja", "ビデオ"),
    ("Video", "ru", "Видео"),
    ("Video", "sr", "Видео"),
    ("Video", "sr-Latn", "Video"),
    ("Video", "zh-Hans", "视频"),
    ("Video message", "de", "Videonachricht"),
    ("Video message", "es", "Mensaje de vídeo"),
    ("Video message", "fr", "Message vidéo"),
    ("Video message", "ja", "ビデオメッセージ"),
    ("Video message", "ru", "Видеосообщение"),
    ("Video message", "sr", "Видео-порука"),
    ("Video message", "sr-Latn", "Video-poruka"),
    ("Video message", "zh-Hans", "视频消息"),
    (
        "You're in — welcome to %@",
        "de",
        "Du bist dabei – willkommen bei %@",
    ),
    (
        "You're in — welcome to %@",
        "es",
        "Ya estás dentro: te damos la bienvenida a %@",
    ),
    (
        "You're in — welcome to %@",
        "fr",
        "C’est fait — bienvenue dans %@",
    ),
    (
        "You're in — welcome to %@",
        "ja",
        "参加しました — %@へようこそ",
    ),
    (
        "You're in — welcome to %@",
        "ru",
        "Ты в семье — добро пожаловать в %@",
    ),
    (
        "You're in — welcome to %@",
        "sr",
        "Ту си — добро дошао/ла у %@",
    ),
    (
        "You're in — welcome to %@",
        "sr-Latn",
        "Tu si — dobro došao/la u %@",
    ),
    (
        "You're in — welcome to %@",
        "zh-Hans",
        "你已加入——欢迎来到 %@",
    ),
];

/// Every language the table speaks, besides English.
pub(crate) static LANGUAGES: &[&str] = &["de", "es", "fr", "ja", "ru", "sr", "sr-Latn", "zh-Hans"];
