#!/usr/bin/env python3
"""What the Windows port of fc_text::markdown and fc_text::links needs from the ORIGINAL, transcribed rather than retyped.

Three outputs, all of them generated and none of them to be edited by hand:

- win/src/FamilyConnect.Core/Text/MarkdownTables.g.cs — cmark's punctuation table, the HTML5 entity table, the case-folding
  exceptions and the two IDNA tables, read out of web/text/src/markdown.rs;
- win/src/FamilyConnect.Core/Text/LinkTables.g.cs — Apple's measured URL tables and the top-level-domain lists, read out of
  web/text/src/links.rs;
- win/src/FamilyConnect.Core/Text/UnicodeProperties.g.cs — the Rust standard library's own character properties
  (`is_alphabetic`, `is_numeric`, `is_lowercase`, `is_uppercase`, `is_whitespace`, `is_control`, `to_lowercase`), printed
  by `board-oracle unicode`. Those two modules decide by Rust's Unicode, and .NET's is a different version with different
  definitions (`Rune.IsLetter` is not the Alphabetic property), so the port decides by the same tables instead;

and the oracle corpus, win/tools/board-oracle/corpus/markdown.json: every string literal in both modules' own tests, then
a fixed-seed run of markup-heavy strings, so the vectors cover what the tests name and what nobody thought to.

Run from anywhere: `python3 win/tools/markdown/transcribe.py`. It changes nothing when nothing upstream changed.
"""
import json
import pathlib
import random
import subprocess

ROOT = pathlib.Path(__file__).resolve().parents[3]
TEXT = ROOT / 'web' / 'text' / 'src'
CORE = ROOT / 'win' / 'src' / 'FamilyConnect.Core' / 'Text'
ORACLE = ROOT / 'win' / 'tools' / 'board-oracle'

HEADER = '// <auto-generated>\n// GENERATED by win/tools/markdown/transcribe.py from {source}. Do not edit: run the script.\n// </auto-generated>\n'


# ---- Rust source -----------------------------------------------------------------------------------------------

def decode_escape(text, index):
    """The character(s) a Rust escape at text[index] (just past the backslash) stands for, and where it ends."""
    c = text[index]
    simple = {'n': '\n', 'r': '\r', 't': '\t', '\\': '\\', '"': '"', "'": "'", '0': '\0'}
    if c in simple:
        return simple[c], index + 1
    if c == 'u':
        close = text.index('}', index)
        return chr(int(text[index + 2:close], 16)), close + 1
    if c == 'x':
        return chr(int(text[index + 1:index + 3], 16)), index + 3
    if c == '\n':
        # A line continuation: the newline and the indentation after it vanish.
        index += 1
        while index < len(text) and text[index] in ' \t\n\r':
            index += 1
        return '', index
    raise ValueError(f'unknown escape \\{c}')


def string_literals(code):
    """Every "..." literal in `code`, decoded — skipping comments and char literals, which a regex cannot."""
    out = []
    i = 0
    n = len(code)
    while i < n:
        c = code[i]
        if code.startswith('//', i):
            i = code.find('\n', i)
            if i < 0:
                break
            continue
        if code.startswith('/*', i):
            i = code.find('*/', i) + 2
            continue
        if c == "'":
            # A char literal ('x', '\n', '\u{1F600}'), or a lifetime, which has no closing quote.
            if i + 2 < n and code[i + 1] == '\\':
                close = code.find("'", i + 2)
                if close > 0 and close - i <= 12:
                    i = close + 1
                    continue
            elif i + 2 < n and code[i + 2] == "'":
                i += 3
                continue
            i += 1
            continue
        if c == 'r' and i + 1 < n and code[i + 1] in '"#' and (i == 0 or not (code[i - 1].isalnum() or code[i - 1] == '_')):
            hashes = 0
            j = i + 1
            while j < n and code[j] == '#':
                hashes += 1
                j += 1
            if j < n and code[j] == '"':
                end = code.index('"' + '#' * hashes, j + 1)
                out.append(code[j + 1:end])
                i = end + 1 + hashes
                continue
        if c == '"':
            value = []
            i += 1
            while code[i] != '"':
                if code[i] == '\\':
                    decoded, i = decode_escape(code, i + 1)
                    value.append(decoded)
                else:
                    value.append(code[i])
                    i += 1
            out.append(''.join(value))
            i += 1
            continue
        i += 1
    return out


def const_block(source, name):
    start = source.index(f'const {name}:')
    open_at = source.index('= &[', start) + 4
    depth = 1
    i = open_at
    while depth:
        if source[i] == '[':
            depth += 1
        elif source[i] == ']':
            depth -= 1
        elif source[i] == '"':
            i += 1
            while source[i] != '"':
                i += 2 if source[i] == '\\' else 1
        i += 1
    return source[open_at:i - 1]


def ranges(block):
    import re
    return [(int(low, 0), int(high, 0)) for low, high in re.findall(r'\((0x[0-9A-Fa-f]+|\d+),\s*(0x[0-9A-Fa-f]+|\d+)\)', block)]


def char_string_pairs(block):
    """('\\u{B5}', "\\u{3BC}") entries, decoded."""
    out = []
    i = 0
    while True:
        i = block.find("('", i)
        if i < 0:
            return out
        j = i + 2
        if block[j] == '\\':
            key, j = decode_escape(block, j + 1)
        else:
            key, j = block[j], j + 1
        assert block[j] == "'", block[i:i + 40]
        value = string_literals(block[j + 1:block.index(')', block.index('"', j + 1) + 1) + 1])
        out.append((key, value[0]))
        i = j + 1


# ---- C# ------------------------------------------------------------------------------------------------------------

def cs_string(value):
    out = ['"']
    for c in value:
        code = ord(c)
        if c == '"':
            out.append('\\"')
        elif c == '\\':
            out.append('\\\\')
        elif 0x20 <= code < 0x7F:
            out.append(c)
        elif code > 0xFFFF:
            out.append('\\U%08X' % code)
        else:
            out.append('\\u%04X' % code)
    out.append('"')
    return ''.join(out)


def cs_ranges(name, doc, values):
    rows = ', '.join(f'(0x{low:X}, 0x{high:X})' for low, high in values)
    return f'    /// <summary>{doc}</summary>\n    public static readonly (int Low, int High)[] {name} = [{rows}];\n'


def cs_strings(name, doc, values):
    return f'    /// <summary>{doc}</summary>\n    public static readonly string[] {name} = [{", ".join(cs_string(v) for v in values)}];\n'


def write_if_changed(path, text):
    if path.exists() and path.read_text(encoding='utf-8') == text:
        print(f'unchanged {path.relative_to(ROOT)}')
        return
    path.write_text(text, encoding='utf-8')
    print(f'wrote {path.relative_to(ROOT)}')


def markdown_tables():
    source = (TEXT / 'markdown.rs').read_text(encoding='utf-8')
    entities = list(zip(*[iter(string_literals(const_block(source, 'HTML_ENTITIES')))] * 2))
    assert entities == sorted(entities, key=lambda pair: pair[0].encode()), 'HTML_ENTITIES must stay sorted by bytes'
    folds = char_string_pairs(const_block(source, 'CASE_FOLD_EXTRA'))
    assert [ord(k) for k, _ in folds] == sorted(ord(k) for k, _ in folds)
    body = [HEADER.format(source='web/text/src/markdown.rs'), 'namespace FamilyConnect.Core;\n\n',
            '/// <summary>The tables fc_text::markdown decides by, transcribed.</summary>\n',
            'public static class MarkdownTables\n{\n']
    body.append(cs_ranges('CmarkPunctuation', "cmark's punctuation above ASCII (<c>CMARK_PUNCTUATION</c>).", ranges(const_block(source, 'CMARK_PUNCTUATION'))))
    body.append('\n    /// <summary>The HTML5 named entities, sorted by their bytes (<c>HTML_ENTITIES</c>).</summary>\n')
    body.append('    public static readonly (string Name, string Value)[] HtmlEntities = [' + ', '.join(f'({cs_string(n)}, {cs_string(v)})' for n, v in entities) + '];\n')
    body.append('\n    /// <summary>Where full case folding is not <c>to_lowercase</c>, sorted by scalar (<c>CASE_FOLD_EXTRA</c>).</summary>\n')
    body.append('    public static readonly (int Scalar, string Folded)[] CaseFoldExtra = [' + ', '.join(f'(0x{ord(k):X}, {cs_string(v)})' for k, v in folds) + '];\n\n')
    body.append(cs_ranges('IdnaRefused', 'What IDNA refuses in a host (<c>IDNA_REFUSED</c>).', ranges(const_block(source, 'IDNA_REFUSED'))))
    body.append('\n')
    body.append(cs_ranges('IdnaIgnored', 'What IDNA removes from a host first (<c>IDNA_IGNORED</c>).', ranges(const_block(source, 'IDNA_IGNORED'))))
    body.append('}\n')
    write_if_changed(CORE / 'MarkdownTables.g.cs', ''.join(body))


def link_tables():
    source = (TEXT / 'links.rs').read_text(encoding='utf-8')
    body = [HEADER.format(source='web/text/src/links.rs'), 'namespace FamilyConnect.Core;\n\n',
            "/// <summary>Apple's measured tables and the domain lists fc_text::links decides by, transcribed.</summary>\n",
            'public static class LinkTables\n{\n']
    body.append(cs_ranges('UrlStop', 'Non-ASCII characters that end a URL (<c>URL_STOP</c>).', ranges(const_block(source, 'URL_STOP'))))
    body.append('\n')
    body.append(cs_ranges('UrlPoison', "Non-ASCII characters that cut a path back to its host (<c>URL_POISON</c>).", ranges(const_block(source, 'URL_POISON'))))
    body.append('\n')
    body.append(cs_ranges('HostBad', 'Non-ASCII characters a path may hold and a host may not (<c>HOST_BAD</c>).', ranges(const_block(source, 'HOST_BAD'))))
    body.append('\n')
    body.append(cs_strings('BareTlds', 'The top-level domains a bare host is linked under (<c>BARE_TLDS</c>).', string_literals(const_block(source, 'BARE_TLDS'))))
    body.append('\n')
    body.append(cs_strings('UnicodeTlds', 'The internationalised ones (<c>UNICODE_TLDS</c>).', string_literals(const_block(source, 'UNICODE_TLDS'))))
    body.append('\n')
    body.append(cs_strings('EmailUnicodeTlds', 'And the ones an email domain may end in on top (<c>EMAIL_UNICODE_TLDS</c>).', string_literals(const_block(source, 'EMAIL_UNICODE_TLDS'))))
    body.append('}\n')
    write_if_changed(CORE / 'LinkTables.g.cs', ''.join(body))


def unicode_properties():
    printed = subprocess.run(['cargo', 'run', '--quiet', '--', 'unicode'], cwd=ORACLE, capture_output=True, text=True, check=True).stdout
    tables = json.loads(printed)
    body = [HEADER.format(source='the Rust standard library, through `board-oracle unicode`'), 'namespace FamilyConnect.Core;\n\n',
            "/// <summary>Rust's <c>char</c> properties over every scalar: what fc_text decides by, so the port decides by the same.</summary>\n",
            'public static class UnicodeProperties\n{\n']
    for key, name in [('alphabetic', 'Alphabetic'), ('numeric', 'Numeric'), ('lowercase', 'Lowercase'), ('uppercase', 'Uppercase'), ('whitespace', 'Whitespace'), ('control', 'Control')]:
        body.append(cs_ranges(name, f'<c>char::is_{key}</c>.', [tuple(pair) for pair in tables[key]]))
        body.append('\n')
    body.append(cs_ranges('GraphemeExtends', 'unicode-segmentation: a scalar that joins the cluster of an ASCII character before it (Extend, ZWJ, SpacingMark).', [tuple(pair) for pair in tables['grapheme_extends']]))
    body.append('\n')
    body.append(cs_ranges('GraphemePrepends', 'unicode-segmentation: a scalar that joins the cluster of an ASCII character after it (Prepend).', [tuple(pair) for pair in tables['grapheme_prepends']]))
    body.append('\n')
    body.append('    /// <summary><c>char::to_uppercase</c> wherever it is not the character itself, sorted by scalar.</summary>\n')
    body.append('    public static readonly (int Scalar, string Upper)[] ToUppercase = [' + ', '.join(f'(0x{scalar:X}, {cs_string(upper)})' for scalar, upper in tables['to_uppercase']) + '];\n\n')
    body.append('    /// <summary><c>char::to_lowercase</c> wherever it is not the character itself, sorted by scalar.</summary>\n')
    body.append('    public static readonly (int Scalar, string Lower)[] ToLowercase = [' + ', '.join(f'(0x{scalar:X}, {cs_string(lower)})' for scalar, lower in tables['to_lowercase']) + '];\n')
    body.append('}\n')
    write_if_changed(CORE / 'UnicodeProperties.g.cs', ''.join(body))


def corpus():
    bodies = []
    seen = set()
    for name in ('markdown.rs', 'links.rs'):
        source = (TEXT / name).read_text(encoding='utf-8')
        tests = source[source.index('#[cfg(test)]'):]
        for literal in string_literals(tests):
            if literal not in seen:
                seen.add(literal)
                bodies.append(literal)
    pieces = ['*', '**', '_', '__', '~', '~~', '`', '```', '[', ']', '(', ')', '<', '>', '!', '^', ':', 'w', 'www.', 'http://',
              'https://', 'mailto:', '@', '.', '#', '# ', '- ', ' ', '  ', '\n', '|', '---', '\\', '&amp;', '&#39;', 'a', 'b', 'x',
              '1', '9', 'é', '日本', 'п', '\U0001F600', ' ', 'ß', 'İ', '​', 'example.com',
              'user@example.com', '555-123-4567', '+44 20 7946 0958', '](', 'tel:', '"', "'"]
    # Bodies the mutation check found the corpus lacked, each the one input that tells a rule apart.
    for body in ['*a*　b', 'a　*b*　c', '_a_ b', '[x](https://xy--é.com)', '[x](https://é--ab.com)',
                 '[x](https://ab-é.com)', 'see example.BO now', 'see example.bo now', 'see example.Bo now', '한국어example.com',
                 'www.example.com한국', 'https://example.com/한국어 ok', '한 user@example.com', 'user@example.com한',
                 '+44 (0)20 7946 0958', '+44 (0) 20 7946 0958', 'call 911-22', 'call 911', 'dial: 12345', 'Call 911-',
                 'a@10.0.0.256', 'a@10.0.0.255', 'a@256.1.1.1', '\U0001F600@ai', '\U0001F600 @ai \U0001F1F7\U0001F1F8 @ai',
                 '\U0001D4B3 **@ai** \U0001F600', '_a_　b', 'x　_a_', '__a__　b', 'https://　x.com',
                 '+1 (0)23 4567', '+44 (0)1 234 56', '+7 (0)12 345 67']:
        if body not in seen:
            seen.add(body)
            bodies.append(body)
    generator = random.Random(64)
    wanted = len(bodies) + 600
    while len(bodies) < wanted:
        body = ''.join(generator.choice(pieces) for _ in range(generator.randint(1, 24)))
        if body not in seen:
            seen.add(body)
            bodies.append(body)
    # Then bodies built from what a bubble lays out around the parser: tables, `@ai` and `/draw`, marks that join clusters.
    blocks = ['| a | b |', '|---|---|', '| :-- | --: |', '|:-:|', '| x | y |', '|', ' | ', '\\|', '@ai', '@AI', '/draw', '/draw ',
              ' a cat', '**', '*', '`', '[x](https://e.com)', '[@ai](x.com)', 'https://example.com', '\n', ' ', 'text', '# ',
              '- ', '```\n', 'www.x.com', 'user@example.com', '555-123-4567', '\u0301', '\u0600', '\u200d', ':', '-', '---',
              '\u00e9', '\t', '\u1fef\u1fef\u1fef', '| a | b |\n|---|---|\n', '\n| h |\n| :-: |\n| 1 |\n', '|x|y|\n|-:|:-|\n|1|2|3|\n',
              '*[a](https://e.com)*[b](https://e.com)', '| [l](https://e.com) | `c` |\n|--|--|\n']
    generator = random.Random(65)
    wanted = len(bodies) + 400
    while len(bodies) < wanted:
        body = ''.join(generator.choice(blocks) for _ in range(generator.randint(1, 16)))
        if body not in seen:
            seen.add(body)
            bodies.append(body)
    path = ORACLE / 'corpus' / 'markdown.json'
    path.parent.mkdir(exist_ok=True)
    write_if_changed(path, json.dumps(bodies, ensure_ascii=False, indent=0) + '\n')
    print(f'corpus: {len(bodies)} bodies')


if __name__ == '__main__':
    markdown_tables()
    link_tables()
    unicode_properties()
    corpus()
